#!/bin/sh

set -e
set -o pipefail

Error () {
  echo "err: $@"
  exit 1
}

read -p "Directory name: " dirname
cd ~/dev
mkdir $dirname 2>&1 >/dev/null || Error "Directory already exists!!"

cd $dirname

read -p "HTML [y/n]: " HTML
read -p "CSS [y/n]: " CSS
read -p "JS [y/n]: " JS
read -p "RUBY [y/n]: " RUBY

if [ "$HTML" = "y" ]; then
  echo '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="">
  <title>'"$dirname"'</title>
</head>
<body>
  <h1>LOL</h1>
</body>
</html>' > index.html
fi

[ "$CSS" = "y" ] && touch main.css
[ "$JS" = "y" ] && touch main.js
[ "$RUBY" = "y" ] && touch app.rb

echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
