#!/bin/sh

set -e
set -o pipefail

dirname=$1

case "$1" in
  # thanks to matti
  "install")
    dir=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )
    target=/usr/local/bin/bake

    if [ ! -e "$target" ]; then
      ln -s $dir/bake $target
      echo "Created symlink in $target"
    else
      echo "Already exists in $target"
      exit 1
    fi

    echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1" | lolcat
  ;;

  "update")
    rm /usr/local/bin/bake
    cd ~/dev/shell
    git pull
    cp ~/dev/shell/bake /usr/local/bin
    echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
  ;;

  "remove")
    rm /usr/local/bin/bake
    echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
    exit 1
  ;;

  "help")
    echo " bake
  install         - places in /usr/local/bin
  update
  remove          - removes from /usr/local/bin
  frontend        - creates HTML/CSS/JS project
  ruby            - creates basic sinatra webapp
  ruby-frontend   - creates basic sinatra with erb view
  node            - creates basic node/express app
    "
      exit 1
    ;;

  "$dirname")
    cd && cd dev
    mkdir $dirname && Error "the directory already exists"
    cd $dirname
  ;;

esac

case "$2" in
  "frontend")
    echo '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="main.css">
  <title>'"$dirname"'</title>
</head>
<body>
  <h1>LOL</h1>
  <script src="main.js"></script>
</body>
</html>' > index.html

  touch main.css
  touch main.js
  echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
  ;;

  "ruby")
    echo 'require "sinatra"

get "/" do
  "bonjour"
end
    ' > app.rb

    # how would I echo the ruby output
    gem install sinatra
    gem install thin
    echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
  ;;

  "ruby-frontend")
    echo 'require "sinatra"

get "/" do
  erb :index
end
    ' > app.rb

    mkdir views && cd views
    echo '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>'"$dirname"'</title>
</head>
<body>
  <h1>bonjour</h1>
</body>
</html>' > index.erb
  echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
  ;;

  "node")
    npm init -y
    npm install --save express body-parser
    echo "var express = require('express')
    var app = express();
    var bodyParser = require('body-parser');

    var port = process.env.PORT || 8080;
    app.listen(port);
    " > index.js

    echo "node_modules
    package-lock.json
    .gitignore
    " > .gitignore

    echo "\xE2\x9A\xA1 Great success!\xE2\x9A\xA1"
    ;;
  esac
